import { useEffect, useRef, useState, type ReactNode } from 'react'
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Check, ChevronDown, ChevronRight, CircleHelp, Download, Flag, FolderOpen, History, Home, Medal, MoreHorizontal, Pencil, Pin, Play, Plus, Search, Settings, ShieldCheck, Sparkles, Trash2, Trophy, Upload, Users, X } from 'lucide-react'
import { useAppNavigation } from '../../lib/navigation'
import { useScrollNav } from '../../lib/use-scroll-nav'
import { useKeyboardVisible } from '../../lib/use-keyboard-visible'
import { canEditRoster, createRoom, decodeLibrary, editRoom, exportBackup, formatBytes, getStorageError, newProfile, playerStats, restoreBackup, roomStatus, savePlayerProfile, saveRoom, startRoom, STORAGE_LIMIT, storageBytes, updateLibrary, useLibrary, type PlayerProfile, type Room } from '../../lib/room-store'
import { bankerPlayerColors } from '../../game/bankerGame'
import { CardArtwork } from '../../components/CardArtwork'
import { ConfirmationModal } from '../../components/ConfirmationModal'
import { PageArtwork } from './PageArtwork'
import { TargetScorePicker, targetScorePresets } from './TargetScorePicker'
import { AppFooter } from './AppFooter'

type MobilePage = 'home' | 'players' | 'history' | 'settings' | 'new' | 'room'
const routes = { home: '/landing', players: '/players', history: '/history', settings: '/settings', new: '/new' }
function dateLabel(timestamp: number) { return new Date(timestamp).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) }
function relativeTime(timestamp: number) { const mins = Math.max(0, Math.floor((Date.now() - timestamp) / 60000)); return mins < 1 ? 'Just now' : mins < 60 ? `${mins}m ago` : mins < 1440 ? `${Math.floor(mins / 60)}h ago` : dateLabel(timestamp) }
function Avatar({ player, small = false }: { player: PlayerProfile; small?: boolean }) { return <span className={`room-avatar ${small ? 'small' : ''}`} style={{ background: player.color }}>{player.name.slice(0, 1).toUpperCase()}</span> }
function EmptyState({ icon, title, children, action }: { icon: ReactNode; title: string; children: ReactNode; action?: ReactNode }) { return <section className="room-empty"><div className="room-empty-icon">{icon}</div><h2>{title}</h2><p>{children}</p>{action}</section> }
function ActionButton({ children, onClick, secondary = false, disabled = false }: { children: ReactNode; onClick?: () => void; secondary?: boolean; disabled?: boolean }) { return <button type="button" className={`room-button ${secondary ? 'secondary' : ''}`} onClick={onClick} disabled={disabled}>{children}</button> }

export function BottomNav({ page }: { page: MobilePage }) {
  const navigate = useAppNavigation()
  const { navRef, hidden, reveal } = useScrollNav(page)
  const keyboardVisible = useKeyboardVisible()
  const tabs = [{ page: 'home', label: 'Home', icon: Home }, { page: 'players', label: 'Players', icon: Users }, { page: 'new', label: 'New room', icon: Plus }, { page: 'history', label: 'History', icon: History }, { page: 'settings', label: 'Settings', icon: Settings }] as const
  const activePage = page === 'room' ? 'home' : page
  return <nav ref={navRef} className={`room-bottom-nav${hidden ? ' is-scroll-hidden' : ''}${keyboardVisible ? ' is-keyboard-hidden' : ''}`} inert={keyboardVisible} onFocusCapture={reveal} aria-label="Main navigation">{tabs.map(item => <button type="button" key={item.page} aria-current={activePage === item.page ? 'page' : undefined} aria-label={item.label} className={`${item.page === 'new' ? 'nav-create' : 'nav-item'} ${activePage === item.page ? 'active' : ''}`} onClick={() => navigate(routes[item.page])}><span className="nav-icon"><item.icon size={item.page === 'new' ? 27 : 22} strokeWidth={2.3} /></span><span className="nav-label">{item.label}</span></button>)}</nav>
}

function RoomCard({ room, feature = false }: { room: Room; feature?: boolean }) {
  const navigate = useAppNavigation()
  const state = room.state
  const leader = state ? [...state.players].sort((a, b) => b.totalScore - a.totalScore)[0] : null
  const progress = state && state.phase !== 'results'
  return <article className={`library-room-card ${feature ? 'featured' : ''} ${state?.phase === 'results' ? 'complete' : ''}`}>
    <div className="room-card-top"><span className={`room-badge ${progress ? 'live' : state ? 'done' : 'ready'}`}>{state && state.phase === 'results' ? <Check size={12} /> : !state ? <Flag size={12} /> : null}{roomStatus(room)}</span><button type="button" className={`room-pin ${room.pinned ? 'pinned' : ''}`} aria-label={`${room.pinned ? 'Unpin' : 'Pin'} ${room.name}`} aria-pressed={room.pinned} onClick={() => { try { saveRoom({ ...room, pinned: !room.pinned }) } catch (error) { window.alert((error as Error).message) } }}><Pin size={17} fill={room.pinned ? 'currentColor' : 'none'} /></button></div>
    <button type="button" className="room-card-title" onClick={() => navigate(`/room?id=${room.id}`)}><h3>{room.name}</h3><ChevronRight size={20} /></button>
    <p className="room-card-meta">{room.roster.length} players <span>·</span> {state ? `${state.history.length} round${state.history.length === 1 ? '' : 's'} played` : `First to ${room.targetScore}`} <span>·</span> {relativeTime(room.updatedAt)}</p>
    <div className="room-card-bottom"><div className="room-avatar-stack">{room.roster.slice(0, 4).map(p => <Avatar key={p.id} player={p} small />)}{room.roster.length > 4 && <span className="room-avatar more">+{room.roster.length - 4}</span>}</div>{progress ? <button className="room-resume" onClick={() => navigate(`/banker?room=${room.id}`)}>Resume <Play size={13} fill="currentColor" /></button> : state ? <span className="room-winner"><Trophy size={14} /> {state.winnerIds.map(id => state.players.find(p => p.id === id)?.name).join(' & ')}</span> : <button className="room-open" onClick={() => navigate(`/room?id=${room.id}`)}>Open room <ArrowRight size={15} /></button>}</div>
    {feature && progress && <div className="room-progress-strip"><span>Round {state.roundNumber}<b>{leader?.name} leads · {leader?.totalScore ?? 0} pts</b></span><div className="room-progress-track"><i style={{ width: `${Math.min(100, (leader?.totalScore ?? 0) / room.targetScore * 100)}%` }} /></div></div>}
  </article>
}

function HomeScreen() {
  const library = useLibrary(); const navigate = useAppNavigation()
  const [filter, setFilter] = useState('all'); const [query, setQuery] = useState('')
  const active = library.rooms.filter(r => r.state && r.state.phase === 'round')
  const sorted = [...library.rooms].sort((a, b) => Number(b.pinned) - Number(a.pinned) || b.updatedAt - a.updatedAt)
  const visible = sorted.filter(r => (filter === 'all' || (filter === 'active' ? r.state?.phase === 'round' : !r.state)) && r.name.toLowerCase().includes(query.toLowerCase()))
  return <><div className="room-home-hero">
    <header className="room-home-header"><img src="/assets/flip7-title-logo.png" alt="Flip7 Companion" /></header>
    <section className="room-welcome"><h1>Your table.<br /><em>Your game night.</em></h1><p>Resume a match or start a new room.</p></section>
  </div>
    <section className="room-create-banner"><div><span className="room-kicker">LET THE GOOD TIMES FLIP</span><h2>A new room.<br />A fresh shot at 200.</h2><button onClick={() => navigate('/new')}>Create a room <ArrowRight size={17} /></button></div><img className="room-promo-art" src="/assets/promo-2.png" alt="" decoding="async" /></section>
    <div className="room-home-stats"><span><b>{library.rooms.length}</b> {library.rooms.length === 1 ? 'room' : 'rooms'}</span><span><b>{library.players.length}</b> {library.players.length === 1 ? 'player' : 'players'}</span><span><b>{library.rooms.filter(r => r.state?.phase === 'results').length}</b> completed</span></div>
    <section className="room-library"><div className="room-section-heading"><h2>Your rooms <span>{library.rooms.length}</span></h2>{active.length > 0 && <span className="room-section-note">{active.length} in progress</span>}</div>
      {library.rooms.length > 0 && <><div className="room-filter-tabs">{[['all', 'All rooms'], ['active', 'In progress'], ['ready', 'Ready to play']].map(([value, label]) => <button key={value} aria-pressed={filter === value} className={filter === value ? 'selected' : ''} onClick={() => setFilter(value)}>{label}</button>)}</div><label className="room-search"><Search size={18} /><input placeholder="Find a room…" aria-label="Search rooms" value={query} onChange={e => setQuery(e.target.value)} /></label></>}
      <div className="room-list">{visible.map((r, i) => <RoomCard key={r.id} room={r} feature={i === 0 && r.state?.phase === 'round'} />)}</div>
      {!library.rooms.length ? <EmptyState icon={<FolderOpen size={30} />} title="Your next game starts here">Create your first room, bring your favorite people, and keep every flip.</EmptyState> : !visible.length && <EmptyState icon={<Search size={28} />} title="No rooms found">Try a different name or filter.</EmptyState>}
    </section></>
}

function PageHeading({ kicker, title, copy, action }: { kicker: string; title: string; copy: string; action?: ReactNode }) { return <header className="room-page-heading"><span className="room-kicker">{kicker}</span><div><h1>{title.replaceAll('\\n', '\n')}</h1>{action}</div><p>{copy}</p></header> }

function PlayerEditor({ profile, onClose }: { profile?: PlayerProfile; onClose: () => void }) {
  const library = useLibrary(); const [name, setName] = useState(profile?.name ?? ''); const [color, setColor] = useState(profile?.color ?? bankerPlayerColors[library.players.length % bankerPlayerColors.length]); const [error, setError] = useState(''); const [deleting, setDeleting] = useState(false)
  const dialogRef = useRef<HTMLDialogElement>(null)
  useEffect(() => { dialogRef.current?.showModal() }, [])
  const submit = () => {
    if (!name.trim()) return setError('Give this player a name.')
    if (library.players.some(p => p.id !== profile?.id && p.name.toLowerCase() === name.trim().toLowerCase())) return setError('There is already a player with that name.')
    try { const player = { ...(profile ?? newProfile(name)), name: name.trim(), color }; savePlayerProfile(player); onClose() } catch (e) { setError((e as Error).message) }
  }
  return <dialog ref={dialogRef} className="room-dialog" onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose() }}><div className="room-dialog-heading"><h2>{profile ? 'Edit player' : 'Meet your next player'}</h2><button className="room-icon-button" aria-label="Close player editor" onClick={onClose}><X size={20} /></button></div><p>A familiar face at every game night.</p><div className="player-avatar-preview"><Avatar player={{ id: '', name: name || '?', color }} /></div><label className="room-field">PLAYER NAME<input autoFocus value={name} maxLength={24} placeholder="What should we call them?" onChange={e => setName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') submit() }} /></label><fieldset className="room-color-picker"><legend>CHOOSE A COLOR</legend>{bankerPlayerColors.map(c => <button key={c} aria-label={`Color ${c}`} aria-pressed={color === c} style={{ background: c }} onClick={() => setColor(c)}>{color === c && <Check size={19} />}</button>)}</fieldset>{error && <p className="room-error" role="alert">{error}</p>}<ActionButton onClick={submit}><Check size={18} /> Save player</ActionButton>{profile && (deleting ? <div className="room-profile-delete"><p>Remove this saved player? Existing rooms and their history keep this player’s original record.</p><div><button onClick={() => setDeleting(false)}>Keep player</button><button onClick={() => { try { updateLibrary(current => ({ ...current, players: current.players.filter(p => p.id !== profile.id) })); onClose() } catch (e) { setError((e as Error).message) } }}>Confirm remove</button></div></div> : <button className="room-delete-player" onClick={() => setDeleting(true)}><Trash2 size={14} /> Remove saved player</button>)}</dialog>
}

function PlayersScreen() {
  const library = useLibrary(); const [query, setQuery] = useState(''); const [editing, setEditing] = useState<PlayerProfile | 'new' | null>(null)
  const players = library.players.filter(p => p.name.toLowerCase().includes(query.toLowerCase()))
  return <><PageHeading kicker="THE GAME NIGHT CREW" title="Players" copy="Your crew and their lifetime records." />
    <label className="room-search"><Search size={18} /><input aria-label="Search players" placeholder="Find a player…" value={query} onChange={e => setQuery(e.target.value)} /></label><div className="room-section-heading"><h2>Your crew <span>{library.players.length}</span></h2></div>
    <button className="room-dashed-action" onClick={() => setEditing('new')}><Plus size={18} /> Add a player</button>
    <div className="room-player-list">{players.map(p => { const stats = playerStats(p.id, library.rooms, library.archivedStats); return <article className="room-profile-card" key={p.id}><Avatar player={p} /><div className="room-profile-copy"><h3>{p.name}</h3><p>{stats.matches} {stats.matches === 1 ? 'match' : 'matches'} <span>·</span> {stats.wins} {stats.wins === 1 ? 'win' : 'wins'}</p><span><Trophy size={12} /> Best score <b>{stats.best || '—'}</b></span></div><button className="room-icon-button" aria-label={`Edit ${p.name}`} onClick={() => setEditing(p)}><Pencil size={17} /></button></article> })}</div>
    {!players.length && <EmptyState icon={<Users size={30} />} title={query ? 'No players found' : 'Save your game night crew'}>{query ? 'Try another name.' : 'Add players here or while creating a room. Their match stats grow as you play.'}</EmptyState>}<p className="room-local-note">Profile edits update this player in saved rooms and games.</p>{editing && <PlayerEditor profile={editing === 'new' ? undefined : editing} onClose={() => setEditing(null)} />}</>
}

function HistoryScreen() {
  const library = useLibrary(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('completed')
  const completed = library.rooms.filter(r => r.state?.phase === 'results')
  const visible = [...library.rooms].filter(r => r.state && (filter === 'all' || r.state.phase === 'results') && (r.name.toLowerCase().includes(query.toLowerCase()) || r.roster.some(p => p.name.toLowerCase().includes(query.toLowerCase())))).sort((a, b) => b.updatedAt - a.updatedAt)
  return <><PageHeading kicker="EVERY FLIP HAS A STORY" title="Match history" copy="Final scores and every round’s cards." /><section className="room-history-banner"><Trophy size={39} /><div><strong>{completed.length}</strong><span>game{completed.length === 1 ? '' : 's'} in the books</span></div><Sparkles size={23} /></section><div className="room-filter-tabs"><button className={filter === 'completed' ? 'selected' : ''} aria-pressed={filter === 'completed'} onClick={() => setFilter('completed')}>Completed</button><button className={filter === 'all' ? 'selected' : ''} aria-pressed={filter === 'all'} onClick={() => setFilter('all')}>All matches</button></div><label className="room-search"><Search size={18} /><input aria-label="Search match history" placeholder="Search rooms or players…" value={query} onChange={e => setQuery(e.target.value)} /></label><div className="room-section-heading"><h2>{filter === 'completed' ? 'Past game nights' : 'Your matches'}</h2><span className="room-section-note">{visible.length} {visible.length === 1 ? 'MATCH' : 'MATCHES'}</span></div><div className="room-list">{visible.map(r => <RoomCard key={r.id} room={r} />)}</div>{!visible.length && <EmptyState icon={<Medal size={32} />} title={query ? 'No matches found' : 'The best is yet to flip'}>{query ? 'Try another room or player name.' : filter === 'completed' ? 'Finish a match to see the final standings and every round’s cards here.' : 'Start a room to begin recording your games.'}</EmptyState>}</>
}

function RoomForm({ room, onDone }: { room?: Room; onDone?: () => void }) {
  const library = useLibrary(); const navigate = useAppNavigation(); const [name, setName] = useState(room?.name ?? ''); const [target, setTarget] = useState(room?.targetScore ?? library.settings.targetScore); const [roster, setRoster] = useState<PlayerProfile[]>(room?.roster ?? []); const [playerName, setPlayerName] = useState(''); const [error, setError] = useState(''); const [showPicker, setShowPicker] = useState(false)
  const addPlayer = (profile?: PlayerProfile) => {
    const nextName = (profile?.name ?? playerName).trim()
    if (!nextName) return setError('Enter a player name first.')
    if (roster.length >= 18) return setError('A room can hold up to 18 players.')
    if (roster.some(p => p.name.toLowerCase() === nextName.toLowerCase())) return setError('That player is already at the table.')
    const existing = library.players.find(p => p.name.toLowerCase() === nextName.toLowerCase())
    setRoster([...roster, profile ?? existing ?? newProfile(nextName, roster.length)]); setPlayerName(''); setError('')
  }
  const move = (index: number, direction: -1 | 1) => { const next = [...roster];[next[index], next[index + direction]] = [next[index + direction], next[index]]; setRoster(next) }
  const save = (begin: boolean) => {
    if (!name.trim()) return setError('Give your room a name.')
    if (roster.length < 3) return setError('Add at least 3 players to start your room.')
    if (!Number.isInteger(target) || target < 50 || target > 500) return setError('Choose a target between 50 and 500 points.')
    try {
      if (room) { editRoom(room, name, target, roster); if (onDone) onDone(); else navigate(`/room?id=${room.id}`); return }
      const created = createRoom(name, target, roster)
      if (begin) { startRoom(created); navigate(`/banker?room=${created.id}`) } else navigate(`/room?id=${created.id}`)
    } catch (e) { setError((e as Error).message) }
  }
  return <><div className="room-back-row"><button onClick={() => { if (room && onDone) onDone(); else navigate(room ? `/room?id=${room.id}` : '/landing') }}><ArrowLeft size={19} /> {room ? 'Back to room' : 'Your rooms'}</button></div><PageHeading kicker="SET UP YOUR TABLE" title={room ? 'Edit room' : 'New room'} copy={room ? 'Update players before the first card of the round.' : 'Name your room and add your players.'} />
    <section className="room-form-panel"><div className="room-form-section-title"><span>01</span><h2>Make it yours</h2><Flag size={21} /></div><label className="room-field">ROOM NAME<input placeholder="Friday night flips" maxLength={40} value={name} onChange={e => setName(e.target.value)} /></label><div className="room-field">TARGET SCORE<div className="room-target-options">{targetScorePresets.map(({ value, label }) => <button key={value} className={target === value ? 'selected' : ''} aria-pressed={target === value} onClick={() => setTarget(value)}>{value}<small>PTS</small><span>{label}</span></button>)}</div><label className="room-custom-target">Custom target<input type="number" min={50} max={500} aria-label="Custom target score" value={target || ''} onChange={e => setTarget(Number(e.target.value))} /></label></div></section>
    <section className="room-form-panel"><div className="room-form-section-title"><span>02</span><h2>Who’s at the table?</h2><b>{roster.length}/18</b></div><p className="room-muted">3–18 players. Arrange your crew in turn order.{room?.state && ' New players join with zero points.'}</p><div className="room-roster">{roster.map((p, i) => <div className="room-roster-row" key={p.id}><span className="room-seat">{String(i + 1).padStart(2, '0')}</span><Avatar player={p} small /><b>{p.name}</b><div className="room-roster-controls"><button aria-label={`Move ${p.name} up`} disabled={i === 0} onClick={() => move(i, -1)}><ArrowUp size={14} /></button><button aria-label={`Move ${p.name} down`} disabled={i === roster.length - 1} onClick={() => move(i, 1)}><ArrowDown size={14} /></button>{(!room?.state || !room.state.players.some(player => player.id === p.id)) && <button aria-label={`Remove ${p.name}`} onClick={() => setRoster(roster.filter(player => player.id !== p.id))}><X size={15} /></button>}</div></div>)}</div>
      <div className="room-add-player"><input aria-label="New player name" maxLength={24} placeholder="Add a player’s name" value={playerName} onChange={e => setPlayerName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); addPlayer() } }} /><button aria-label="Add named player" disabled={roster.length >= 18} onClick={() => addPlayer()}><Plus size={20} /></button></div>
      {library.players.length > 0 && <><button className="room-pick-crew" aria-expanded={showPicker} onClick={() => setShowPicker(!showPicker)}><Users size={16} /> Choose saved players <ChevronDown size={15} /></button>{showPicker && <div className="room-saved-player-picker">{library.players.filter(p => !roster.some(r => r.id === p.id || r.name.toLowerCase() === p.name.toLowerCase())).map(p => <button key={p.id} onClick={() => addPlayer(p)}><Avatar player={p} small />{p.name}<Plus size={14} /></button>)}{library.players.every(p => roster.some(r => r.id === p.id)) && <p>Everyone’s at the table!</p>}</div>}</>}
    </section>{error && <p className="room-error" role="alert">{error}</p>}<div className="room-form-actions"><ActionButton onClick={() => save(!room)}><Play size={17} fill="currentColor" /> {room ? 'Save room changes' : 'Create & start playing'}</ActionButton>{!room && <ActionButton secondary onClick={() => save(false)}><FolderOpen size={17} /> Save room for later</ActionButton>}</div></>
}

function RoomDetail({ room }: { room: Room }) {
  const navigate = useAppNavigation(); const [editing, setEditing] = useState(false); const [menu, setMenu] = useState(false); const [deletePrompt, setDeletePrompt] = useState(false); const [error, setError] = useState(''); const [tab, setTab] = useState('scores')
  const state = room.state; const editable = canEditRoster(room)
  if (editing && editable) return <RoomForm room={room} onDone={() => { setEditing(false); window.requestAnimationFrame(() => window.scrollTo({ top: 0, behavior: 'auto' })) }} />
  const play = () => { try { if (!state) startRoom(room); navigate(`/banker?room=${room.id}`) } catch (e) { setError((e as Error).message) } }
  const rematch = () => { try { const next = createRoom(`${room.name.slice(0, 30)} · Rematch`, room.targetScore, room.roster); navigate(`/room?id=${next.id}`) } catch (e) { setError((e as Error).message) } }
  const ordered = state ? [...state.players].sort((a, b) => b.totalScore - a.totalScore) : room.roster.map(p => ({ ...p, totalScore: 0 }))
  return <><div className="room-back-row"><button className="room-back-link" onClick={() => navigate('/landing')}><ArrowLeft size={19} /> Your rooms</button><div className="room-menu-wrapper"><button className="room-menu-trigger" aria-label="Room options" aria-expanded={menu} onClick={() => setMenu(!menu)}><MoreHorizontal size={19} /></button>{menu && <><div className="room-menu-backdrop" onClick={() => setMenu(false)} /><div className="room-options-popover" role="menu"><button className="room-delete-button" role="menuitem" onClick={() => { setMenu(false); setDeletePrompt(true) }}><Trash2 size={14} /> Delete room</button></div></>}</div></div>
    <section className="room-detail-hero"><span className={`room-badge ${state?.phase === 'results' ? 'done' : state ? 'live' : 'ready'}`}>{roomStatus(room)}</span><h1>{room.name}</h1><p>{room.roster.length} players <span>·</span> First to {room.targetScore} <span>·</span> {dateLabel(room.createdAt)}</p><div className="room-avatar-stack">{room.roster.slice(0, 8).map(p => <Avatar key={p.id} player={p} small />)}</div>{state?.phase === 'results' ? <ActionButton onClick={rematch}><Plus size={18} /> Same crew, new match</ActionButton> : <ActionButton onClick={play}><Play size={17} fill="currentColor" /> {state ? `Resume round ${state.roundNumber}` : 'Start this game'}</ActionButton>}</section>
    {error && <p className="room-error" role="alert">{error}</p>}{editable && <button className="room-dashed-action" onClick={() => setEditing(true)}><Pencil size={16} /> Edit room & players</button>}
    <div className="room-filter-tabs detail-tabs"><button className={tab === 'scores' ? 'selected' : ''} onClick={() => setTab('scores')} aria-pressed={tab === 'scores'}><Trophy size={15} /> Standings</button><button className={tab === 'rounds' ? 'selected' : ''} onClick={() => setTab('rounds')} aria-pressed={tab === 'rounds'}><History size={15} /> Round history</button></div>
    {tab === 'scores' ? <><div className="room-section-heading"><h2>{state?.phase === 'results' ? 'Final standings' : 'The race so far'}</h2><span className="room-section-note">{state?.history.length ?? 0} ROUNDS</span></div><div className="room-standings">{ordered.map((p, i) => <div className={`room-standing ${state?.winnerIds.includes(p.id) ? 'winner' : ''}`} key={p.id}><span className="standing-rank">{state?.winnerIds.includes(p.id) ? <Trophy size={18} /> : String(i + 1).padStart(2, '0')}</span><Avatar player={p} small /><b>{p.name}</b><strong>{p.totalScore}<small>PTS</small></strong></div>)}</div>{state && <p className="room-local-note">Totals include completed rounds.</p>}</> : <><div className="room-section-heading"><h2>Every round. Every card.</h2></div>{state?.history.length ? [...state.history].reverse().map(round => <details className="room-round-detail" key={round.round}><summary><span className="round-number">{String(round.round).padStart(2, '0')}</span><div><b>Round {round.round}</b><small>{Object.keys(round.scores).length} players · scores & cards</small></div><ChevronDown size={19} /></summary><div className="room-round-hands">{Object.entries(round.scores).map(([id, score]) => { const hand = round.hands?.[id]; const player = hand ? { id, name: hand.name, color: hand.color } : room.roster.find(p => p.id === id); return <article className="room-history-hand" key={id}><header>{player && <Avatar player={player} small />}<b>{player?.name ?? 'Player'}</b><span className={`${hand?.status ?? 'stayed'}-label`}>{hand?.status === 'busted' ? 'BUST' : hand?.status === 'flip-seven' ? 'FLIP 7!' : hand?.status === 'frozen' ? 'FROZEN' : 'BANKED'}</span><strong>{score}<small>pts</small></strong></header><div className="room-history-cards">{hand?.entries.map(entry => <div className={entry.voided ? 'voided' : ''} key={entry.instanceId} title={entry.voided ? `${entry.card.label} · discarded` : entry.card.label}><CardArtwork card={entry.card} lazy />{entry.voided && <span>DISCARDED</span>}</div>)}{!hand?.entries.length && <p>No cards recorded.</p>}</div></article> })}</div></details>) : <EmptyState icon={<History size={29} />} title="Your story starts on round one">Finish a round to save each player’s score and cards here.</EmptyState>}{state?.phase === 'round' && <div className="room-current-note"><Play size={16} /><p>Round {state.roundNumber} is saved and waiting.<button onClick={play}>Back to the table <ArrowRight size={13} /></button></p></div>}</>}
    {deletePrompt && <ConfirmationModal eyebrow="DELETE ROOM" title={`Delete ${room.name}?`} message="This removes this room and its detailed match history. Saved player profiles and lifetime matches, wins, and best scores stay. Export a backup first if you want to keep the details." confirmLabel="Delete room" onCancel={() => setDeletePrompt(false)} onConfirm={() => { try { updateLibrary(current => ({ ...current, rooms: current.rooms.filter(r => r.id !== room.id) })); navigate('/landing') } catch (e) { setError((e as Error).message); setDeletePrompt(false) } }} />}</>
}

function SettingsScreen() {
  const library = useLibrary(); const navigate = useAppNavigation(); const input = useRef<HTMLInputElement>(null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [restore, setRestore] = useState<string | null>(null); const [clear, setClear] = useState(false)
  const bytes = storageBytes(library); const completed = library.rooms.filter(r => r.state?.phase === 'results').length
  const update = (change: Parameters<typeof updateLibrary>[0]) => { try { updateLibrary(change); setError('') } catch (e) { setError((e as Error).message) } }
  const readBackup = async (file?: File) => { if (!file) return; try { if (file.size > STORAGE_LIMIT * 2) throw new Error('The backup file is too large.'); const raw = await file.text(); if (storageBytes(decodeLibrary(raw)) > STORAGE_LIMIT) throw new Error('This backup exceeds the 10 MB game-data limit.'); setRestore(raw); setError('') } catch (e) { setError(`Could not read backup. ${(e as Error).message}`) } if (input.current) input.current.value = '' }
  return <><PageHeading kicker="YOUR GAME, YOUR WAY" title="Settings" copy="Preferences, backups, and help." /><section className="room-storage-panel"><div className="room-section-heading"><h2><ShieldCheck size={21} /> Device storage</h2></div><p>Game data stays on this device.</p><div className="storage-usage"><strong>{formatBytes(bytes)}</strong><span>used · {formatBytes(STORAGE_LIMIT)} save limit</span></div><div className="room-progress-track"><i style={{ width: `${Math.min(100, Math.max(1, bytes / STORAGE_LIMIT * 100))}%` }} /></div><div className="storage-counts"><span>{library.rooms.length} {library.rooms.length === 1 ? 'room' : 'rooms'}</span><span>{library.players.length} {library.players.length === 1 ? 'player' : 'players'}</span><span>{completed} completed</span></div><p className="storage-explanation">Clearing completed rooms keeps lifetime player stats. Card artwork is bundled once. Actual device storage limits may be lower.</p></section>
    <section className="room-settings-group"><h2>At your table</h2><div className="room-setting-row"><div><Flag size={20} /><span><b>Default target score</b><small>For your next room</small></span></div><TargetScorePicker value={library.settings.targetScore} onChange={targetScore => update(current => ({ ...current, settings: { ...current.settings, targetScore } }))} /></div><div className="room-setting-row"><div><Sparkles size={20} /><span><b>Calmer animations</b><small>A little less movement</small></span></div><button role="switch" aria-checked={library.settings.reducedMotion} aria-label="Calmer animations" className={`room-switch ${library.settings.reducedMotion ? 'on' : ''}`} onClick={() => update(current => ({ ...current, settings: { ...current.settings, reducedMotion: !current.settings.reducedMotion } }))}><span /></button></div></section>
    <section className="room-settings-group"><h2>Keep your memories</h2><button className="room-setting-row" onClick={() => { try { exportBackup(); setNotice('Backup download requested. Keep the JSON file somewhere safe.') } catch (e) { setError((e as Error).message) } }}><div><Download size={20} /><span><b>Export a backup</b><small>Take your rooms and players with you</small></span></div><ChevronRight size={18} /></button><button className="room-setting-row" onClick={() => input.current?.click()}><div><Upload size={20} /><span><b>Restore a backup</b><small>Replace local data from a saved file</small></span></div><ChevronRight size={18} /></button><input ref={input} className="visually-hidden" type="file" accept=".json,application/json" aria-label="Backup file" onChange={e => void readBackup(e.target.files?.[0])} /><button className="room-setting-row danger" disabled={!completed} onClick={() => setClear(true)}><div><Trash2 size={20} /><span><b>Clear completed rooms</b><small>Keep every unfinished game</small></span></div><ChevronRight size={18} /></button></section>
    <section className="room-settings-group"><h2>A little help</h2>{[['How to play', '/rules', CircleHelp], ['Practice table', '/demo', Play], ['Questions & answers', '/faq', CircleHelp], ['Privacy & local data', '/privacy', ShieldCheck], ['Terms & conditions', '/terms', ShieldCheck], ['Contact & feedback', '/contact', CircleHelp]].map(([label, path, Icon]) => { const I = Icon as typeof CircleHelp; return <button key={String(path)} className="room-setting-row" onClick={() => navigate(String(path))}><div><I size={20} /><b>{String(label)}</b></div><ChevronRight size={18} /></button> })}</section>{error && <p className="room-error" role="alert">{error}</p>}{notice && <p className="room-success" role="status">{notice}</p>}<AppFooter />
    {restore && <ConfirmationModal eyebrow="RESTORE BACKUP" title="Replace your local library?" message="Rooms, player profiles, lifetime stats, and preferences will be replaced by this backup. Export your current library first if you want to keep it." confirmLabel="Restore backup" onCancel={() => setRestore(null)} onConfirm={() => { try { restoreBackup(restore); setNotice('Backup restored. Your rooms are ready.'); setRestore(null) } catch (e) { setError((e as Error).message); setRestore(null) } }} />}{clear && <ConfirmationModal eyebrow="FREE UP SPACE" title={`Clear ${completed} completed rooms?`} message="Detailed scores and card history will be removed. Lifetime matches, wins, and best scores stay, along with unfinished games and player profiles. Export a backup first to keep the details." confirmLabel="Clear completed" onCancel={() => setClear(false)} onConfirm={() => { try { updateLibrary(current => ({ ...current, rooms: current.rooms.filter(r => r.state?.phase !== 'results') })); setError(''); setNotice('Completed history cleared. Lifetime player stats kept.'); setClear(false) } catch (e) { setError((e as Error).message); setClear(false) } }} />}</>
}

export function MobileApp({ page, roomId }: { page: MobilePage; roomId?: string }) {
  const library = useLibrary(); const error = getStorageError(); const navigate = useAppNavigation()
  const room = library.rooms.find(r => r.id === roomId)
  useEffect(() => { document.documentElement.classList.add('room-app-active'); return () => { document.documentElement.classList.remove('room-app-active') } }, [])
  return <div className="room-app-shell"><main className={`room-app-main page-${page}`}>{page !== 'room' && <PageArtwork />}{error && <p className="room-error" role="alert">{error}</p>}{page === 'home' ? <HomeScreen /> : page === 'players' ? <PlayersScreen /> : page === 'history' ? <HistoryScreen /> : page === 'settings' ? <SettingsScreen /> : page === 'new' ? <RoomForm /> : room ? <RoomDetail key={room.id} room={room} /> : <EmptyState icon={<FolderOpen size={30} />} title="This room isn’t here">It may have been removed or restored from a different backup.<ActionButton onClick={() => navigate('/landing')}>Back to your rooms</ActionButton></EmptyState>}</main><BottomNav page={page} /></div>
}
