import { useEffect, useRef, useState, type ReactNode } from 'react'
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Check, ChevronDown, ChevronRight, CircleHelp, Download, Flag, FolderOpen, History, Home, Medal, Monitor, MoreHorizontal, Pencil, Pin, Play, Plus, Search, Settings, ShieldCheck, Sparkles, Trash2, Trophy, Upload, Users, X } from 'lucide-react'
import { useAppNavigation } from '../../lib/navigation'
import { useScrollNav } from '../../lib/use-scroll-nav'
import { useKeyboardVisible } from '../../lib/use-keyboard-visible'
import { canEditRoster, createRoom, decodeLibrary, editRoom, exportBackup, formatBytes, getStorageError, newProfile, playerStats, restoreBackup, roomStatus, savePlayerProfile, saveRoom, startRoom, STORAGE_LIMIT, storageBytes, updateLibrary, useLibrary, type Edition, type PlayerProfile, type Room } from '../../lib/room-store'
import { bankerPlayerColors } from '../../game/bankerGame'
import { cardThumbnailUrl } from '../../game/cardThumbnailUrl'
import { CardArtwork } from '../../components/CardArtwork'
import { ConfirmationModal } from '../../components/ConfirmationModal'
import { PageArtwork } from './PageArtwork'
import { TargetScorePicker, targetScorePresets } from './TargetScorePicker'
import { AppFooter } from './AppFooter'
import { HomePromoCarousel } from './HomePromoCarousel'
import { tvSharingAvailable } from '../../lib/tv-share'
import { TvShareDialog } from './TvShareDialog'
import { PlayerAvatar } from '../../components/PlayerAvatar'
import { EditionFab } from './EditionFab'
import { defaultPlayerAvatarFor, playerAvatars, type PlayerAvatarId } from '../../lib/player-avatars'

type MobilePage = 'home' | 'players' | 'history' | 'settings' | 'new' | 'room'
const routes = { home: '/landing', players: '/players', history: '/history', settings: '/settings', new: '/new' }
function dateLabel(timestamp: number) { return new Date(timestamp).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) }
function relativeTime(timestamp: number) { const mins = Math.max(0, Math.floor((Date.now() - timestamp) / 60000)); return mins < 1 ? 'just now' : mins < 60 ? `${mins}m ago` : mins < 1440 ? `${Math.floor(mins / 60)}h ago` : `${Math.floor(mins / 1440)}d ago` }
function Avatar({ player, small = false }: { player: PlayerProfile; small?: boolean }) { return <PlayerAvatar player={player} className={`room-avatar ${small ? 'small' : ''}`} /> }
const roomState = (room: Room) => room.edition === 'vengeance' ? room.vengeanceState : room.state
const roomPlayPath = (room: Room) => `${room.edition === 'vengeance' ? '/vengeance' : '/banker'}?room=${room.id}`
const currentEdition = (library: ReturnType<typeof useLibrary>): Edition => library.settings.edition
function EmptyState({ icon, title, children, action }: { icon: ReactNode; title: string; children: ReactNode; action?: ReactNode }) { return <section className="room-empty"><div className="room-empty-icon">{icon}</div><h2>{title}</h2><p>{children}</p>{action}</section> }
function ActionButton({ children, onClick, secondary = false, disabled = false }: { children: ReactNode; onClick?: () => void; secondary?: boolean; disabled?: boolean }) { return <button type="button" className={`room-button ${secondary ? 'secondary' : ''}`} onClick={onClick} disabled={disabled}>{children}</button> }

export function BottomNav({ page }: { page: MobilePage }) {
  const navigate = useAppNavigation()
  const { navRef, hidden, reveal } = useScrollNav(page)
  const keyboardVisible = useKeyboardVisible()
  const tabs = [{ page: 'home', label: 'Home', icon: Home }, { page: 'players', label: 'Players', icon: Users }, { page: 'new', label: 'New room', icon: Plus }, { page: 'history', label: 'History', icon: History }, { page: 'settings', label: 'Settings', icon: Settings }] as const
  const activePage = page === 'room' ? 'home' : page
  return <nav ref={navRef} className={`room-bottom-nav${hidden ? ' is-scroll-hidden' : ''}${keyboardVisible ? ' is-keyboard-hidden' : ''}`} inert={keyboardVisible} onFocusCapture={reveal} aria-label="Main navigation">{tabs.map(item => <button type="button" key={item.page} aria-current={activePage === item.page ? 'page' : undefined} aria-label={item.label} className={`${item.page === 'new' ? 'nav-create' : 'nav-item'} ${activePage === item.page ? 'active' : ''}`} onClick={() => navigate(routes[item.page])}><span className="nav-icon"><item.icon size={item.page === 'new' ? 27 : 22} strokeWidth={2.3} /></span><span className="nav-label">{item.label}</span></button>)}</nav>
}

function RoomCard({ room, feature = false }: { room: Room; feature?: boolean }) {
  const navigate = useAppNavigation()
  const state = roomState(room)
  const topScore = state ? Math.max(...state.players.map(player => player.totalScore)) : 0
  const leaders = state?.players.filter(player => player.totalScore === topScore) ?? []
  const leadLabel = leaders.length === 1 ? `${leaders[0].name} leads` : leaders.length === state?.players.length ? 'All tied' : 'Lead tied'
  const progress = state && state.phase !== 'results'
  return <article className={`library-room-card ${feature ? 'featured' : ''} ${state?.phase === 'results' ? 'complete' : ''}`}>
    <div className="room-card-top"><span className={`room-badge ${progress ? 'live' : state ? 'done' : 'ready'}`}>{state && state.phase === 'results' ? <Check size={12} /> : !state ? <Flag size={12} /> : null}{roomStatus(room)}</span><button type="button" className={`room-pin ${room.pinned ? 'pinned' : ''}`} aria-label={`${room.pinned ? 'Unpin' : 'Pin'} ${room.name}`} aria-pressed={room.pinned} onClick={() => { try { saveRoom({ ...room, pinned: !room.pinned }) } catch (error) { window.alert((error as Error).message) } }}><Pin size={17} fill={room.pinned ? 'currentColor' : 'none'} /></button></div>
    <button type="button" className="room-card-title" onClick={() => navigate(`/room?id=${room.id}`)}><h3>{room.name}</h3><ChevronRight size={20} /></button>
    <p className="room-card-meta">{room.roster.length} players <span>·</span> {state ? `${state.history.length} round${state.history.length === 1 ? '' : 's'} played` : `First to ${room.targetScore}`} <span>·</span> <time dateTime={new Date(room.createdAt).toISOString()} title={`Created ${new Date(room.createdAt).toLocaleString()}`}>Created {relativeTime(room.createdAt)}</time></p>
    <div className="room-card-bottom"><div className="room-avatar-stack">{room.roster.slice(0, room.roster.length <= 5 ? 5 : 4).map(p => <Avatar key={p.id} player={p} small />)}{room.roster.length > 5 && <span className="room-avatar more">+{room.roster.length - 4}</span>}</div>{progress ? <button className="room-resume" onClick={() => navigate(roomPlayPath(room))}>Resume <Play size={13} fill="currentColor" /></button> : state ? <span className="room-winner"><Trophy size={14} /> {state.winnerIds.map(id => state.players.find(p => p.id === id)?.name).join(' & ')}</span> : <button className="room-open" onClick={() => navigate(`/room?id=${room.id}`)}>Open room <ArrowRight size={15} /></button>}</div>
    {feature && progress && <div className="room-progress-strip"><span>Round {state.roundNumber}<b>{leadLabel} · {topScore} pts</b></span><div className="room-progress-track"><i style={{ width: `${Math.min(100, topScore / room.targetScore * 100)}%` }} /></div></div>}
  </article>
}

function HomeScreen() {
  const library = useLibrary(); const navigate = useAppNavigation()
  const edition = currentEdition(library)
  const rooms = library.rooms.filter(room => (room.edition ?? 'classic') === edition)
  const [filter, setFilter] = useState('all'); const [query, setQuery] = useState('')
  const active = rooms.filter(r => roomState(r) && roomState(r)?.phase !== 'results')
  const sorted = [...rooms].sort((a, b) => Number(b.pinned) - Number(a.pinned) || b.updatedAt - a.updatedAt)
  const visible = sorted.filter(r => (filter === 'all' || (filter === 'active' ? roomState(r) && roomState(r)?.phase !== 'results' : !roomState(r))) && r.name.toLowerCase().includes(query.toLowerCase()))
  return <><div className="room-home-hero">
    <header className="room-home-header"><img src="/assets/flip7-title-logo.webp" alt="Flip7 Companion" /></header>
    <section className="room-welcome"><h1>{edition === 'vengeance' ? <>No one’s safe.<br /><em>Watch your back.</em></> : <>Your table.<br /><em>Your game night.</em></>}</h1><p>Resume a match or start a new room.</p></section>
  </div>
    <HomePromoCarousel edition={edition} />
    <div className="room-home-stats"><span><b>{rooms.length}</b> {rooms.length === 1 ? 'room' : 'rooms'}</span><span><b>{edition === 'vengeance' ? library.vengeancePlayers.length : library.players.length}</b> {(edition === 'vengeance' ? library.vengeancePlayers.length : library.players.length) === 1 ? 'player' : 'players'}</span><span><b>{rooms.filter(r => roomState(r)?.phase === 'results').length}</b> completed</span></div>
    <section className="room-library"><div className="room-section-heading"><h2>Your rooms <span>{rooms.length}</span></h2>{active.length > 0 && <span className="room-section-note">{active.length} in progress</span>}</div>
      {rooms.length > 0 && <><div className="room-filter-tabs">{[['all', 'All rooms'], ['active', 'In progress'], ['ready', 'Ready to play']].map(([value, label]) => <button key={value} aria-pressed={filter === value} className={filter === value ? 'selected' : ''} onClick={() => setFilter(value)}>{label}</button>)}</div><label className="room-search"><Search size={18} /><input placeholder="Find a room…" aria-label="Search rooms" value={query} onChange={e => setQuery(e.target.value)} /></label></>}
      <div className="room-list">{visible.map((r, i) => <RoomCard key={r.id} room={r} feature={i === 0 && r.state?.phase === 'round'} />)}</div>
      {!rooms.length ? <EmptyState icon={<FolderOpen size={30} />} title="Your next game starts here">Create your first room, bring your favorite people, and keep every flip.</EmptyState> : !visible.length && <EmptyState icon={<Search size={28} />} title="No rooms found">Try a different name or filter.</EmptyState>}
    </section></>
}

function PageHeading({ kicker, title, copy, action }: { kicker: string; title: string; copy: string; action?: ReactNode }) { return <header className="room-page-heading"><span className="room-kicker">{kicker}</span><div><h1>{title.replaceAll('\\n', '\n')}</h1>{action}</div><p>{copy}</p></header> }

function AvatarPicker({ avatar, onChange, color }: { avatar: PlayerAvatarId; onChange: (avatar: PlayerAvatarId) => void; color: string }) {
  const [group, setGroup] = useState<(typeof playerAvatars)[number]['group']>(playerAvatars.find(option => option.id === avatar)?.group ?? 'Any style')
  return <fieldset className="room-avatar-picker">
    <legend>CHOOSE A CHARACTER</legend>
    <div className="room-avatar-tabs" role="group" aria-label="Character styles">
      {(['Any style', 'Male', 'Female'] as const).map(value => <button type="button" key={value} aria-pressed={group === value} onClick={() => setGroup(value)}>{value}</button>)}
    </div>
    <div className="room-avatar-options">
      {playerAvatars.filter(option => option.group === group).map(option => <button type="button" key={option.id} aria-label={`${option.label}, ${group}`} aria-pressed={avatar === option.id} onClick={() => onChange(option.id)}><PlayerAvatar player={{ name: option.label, color, avatar: option.id }} />{avatar === option.id && <Check size={13} className="room-avatar-check" />}</button>)}
    </div>
  </fieldset>
}

function ColorPicker({ color, onChange }: { color: string; onChange: (color: string) => void }) {
  return <fieldset className="room-color-picker"><legend>CHOOSE A COLOR</legend>{bankerPlayerColors.map(option => <button type="button" key={option} aria-label={`Color ${option}`} aria-pressed={color === option} style={{ background: option }} onClick={() => onChange(option)}>{color === option && <Check size={19} />}</button>)}</fieldset>
}

function PlayerEditor({ profile, onClose }: { profile?: PlayerProfile; onClose: () => void }) {
  const library = useLibrary(); const edition = library.settings.edition; const profiles = edition === 'vengeance' ? library.vengeancePlayers : library.players; const [name, setName] = useState(profile?.name ?? ''); const [color, setColor] = useState(profile?.color ?? bankerPlayerColors[profiles.length % bankerPlayerColors.length]); const [avatar, setAvatar] = useState(profile?.avatar ?? defaultPlayerAvatarFor(profile?.id, profiles.length)); const [error, setError] = useState(''); const [deleting, setDeleting] = useState(false)
  const dialogRef = useRef<HTMLDialogElement>(null); const deleteDialogRef = useRef<HTMLDialogElement>(null)
  useEffect(() => { dialogRef.current?.showModal() }, [])
  useEffect(() => { if (deleting) deleteDialogRef.current?.showModal() }, [deleting])
  const submit = () => {
    if (!name.trim()) return setError('Give this player a name.')
    if (profiles.some(p => p.id !== profile?.id && p.name.toLowerCase() === name.trim().toLowerCase())) return setError('There is already a player with that name.')
    try { const player = { ...(profile ?? newProfile(name, profiles.length)), name: name.trim(), color, avatar }; savePlayerProfile(player, edition); onClose() } catch (e) { setError((e as Error).message) }
  }
  return <dialog ref={dialogRef} className="room-dialog" onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose() }}><div className="room-dialog-heading"><h2>{profile ? 'Edit player' : 'Meet your next player'}</h2><button className="room-icon-button" aria-label="Close player editor" onClick={onClose}><X size={20} /></button></div><p>A familiar face at every game night.</p><div className="player-avatar-preview"><Avatar player={{ id: '', name: name || '?', color, avatar }} /></div><label className="room-field">PLAYER NAME<input value={name} maxLength={24} placeholder="What should we call them?" onChange={e => setName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') submit() }} /></label><AvatarPicker avatar={avatar} onChange={setAvatar} color={color} /><ColorPicker color={color} onChange={setColor} />{error && <p className="room-error" role="alert">{error}</p>}<div className={`room-editor-actions${profile ? ' has-profile' : ''}`}>{profile && <button type="button" className="room-delete-player" onClick={() => setDeleting(true)}><Trash2 size={16} /> Remove player</button>}<ActionButton onClick={submit}><Check size={18} /> Save player</ActionButton></div>{deleting && profile && <dialog ref={deleteDialogRef} className="room-delete-confirm-dialog" onCancel={() => setDeleting(false)} onClick={event => { if (event.target === event.currentTarget) setDeleting(false) }}><section className="room-profile-delete-confirm" role="alertdialog" aria-modal="true" aria-labelledby="remove-player-title" aria-describedby="remove-player-copy"><div className="room-profile-delete-heading"><span>REMOVE SAVED PLAYER</span><strong id="remove-player-title">Remove {profile.name}?</strong></div><p id="remove-player-copy">This removes the saved player from your crew. Existing rooms and match history keep their records.</p><div className="room-profile-delete-actions"><button type="button" autoFocus onClick={() => setDeleting(false)}>Keep player</button><button type="button" onClick={() => { try { updateLibrary(current => edition === 'vengeance' ? { ...current, vengeancePlayers: current.vengeancePlayers.filter(p => p.id !== profile.id) } : { ...current, players: current.players.filter(p => p.id !== profile.id) }); onClose() } catch (e) { setError((e as Error).message); setDeleting(false) } }}><Trash2 size={16} /> Remove player</button></div></section></dialog>}</dialog>
}

function RoomCharacterDialog({ player, onClose, onSave }: { player: PlayerProfile; onClose: () => void; onSave: (avatar: PlayerAvatarId, color: string) => void }) {
  const [avatar, setAvatar] = useState(player.avatar ?? defaultPlayerAvatarFor(player.id))
  const [color, setColor] = useState(player.color)
  const [error, setError] = useState('')
  const dialogRef = useRef<HTMLDialogElement>(null)
  useEffect(() => { dialogRef.current?.showModal() }, [])
  return <dialog ref={dialogRef} className="room-dialog room-character-dialog" onCancel={onClose} onClick={event => { if (event.target === event.currentTarget) onClose() }}>
    <div className="room-dialog-heading"><h2>Edit character</h2><button type="button" className="room-icon-button" aria-label="Close character editor" onClick={onClose}><X size={20} /></button></div>
    <p>Choose a character and color for {player.name}.</p>
    <div className="player-avatar-preview"><Avatar player={{ ...player, avatar, color }} /></div>
    <AvatarPicker avatar={avatar} onChange={setAvatar} color={color} />
    <ColorPicker color={color} onChange={setColor} />
    {error && <p className="room-error" role="alert">{error}</p>}
    <div className="room-character-actions"><button type="button" className="room-button secondary" onClick={onClose}>Cancel</button><ActionButton onClick={() => { try { onSave(avatar, color); onClose() } catch (cause) { setError((cause as Error).message) } }}><Check size={16} /> Save character</ActionButton></div>
  </dialog>
}

function PlayersScreen() {
  const library = useLibrary(); const [query, setQuery] = useState(''); const [editing, setEditing] = useState<PlayerProfile | 'new' | null>(null)
  const edition = currentEdition(library)
  const profiles = edition === 'vengeance' ? library.vengeancePlayers : library.players
  const players = profiles.filter(p => p.name.toLowerCase().includes(query.toLowerCase()))
  return <><PageHeading kicker="THE GAME NIGHT CREW" title="Players" copy="Your crew and their lifetime records." />
    <label className="room-search"><Search size={18} /><input aria-label="Search players" placeholder="Find a player…" value={query} onChange={e => setQuery(e.target.value)} /></label><div className="room-section-heading"><h2>Your crew <span>{profiles.length}</span></h2></div>
    <button className="room-dashed-action" onClick={() => setEditing('new')}><Plus size={18} /> Add a player</button>
    <div className="room-player-list">{players.map(p => { const stats = playerStats(p.id, library.rooms, edition === 'vengeance' ? library.vengeanceArchivedStats : library.archivedStats, edition); return <article className="room-profile-card" key={p.id}><Avatar player={p} /><div className="room-profile-copy"><h3>{p.name}</h3><p>{stats.matches} {stats.matches === 1 ? 'match' : 'matches'} <span>·</span> {stats.wins} {stats.wins === 1 ? 'win' : 'wins'}</p><span><Trophy size={12} /> Best score <b>{stats.best || '—'}</b></span></div><button className="room-icon-button" aria-label={`Edit ${p.name}`} onClick={() => setEditing(p)}><Pencil size={17} /></button></article> })}</div>
    {!players.length && <EmptyState icon={<Users size={30} />} title={query ? 'No players found' : 'Save your game night crew'}>{query ? 'Try another name.' : 'Add players here or while creating a room. Their match stats grow as you play.'}</EmptyState>}<p className="room-local-note">Profile edits update this player in saved rooms and games.</p>{editing && <PlayerEditor profile={editing === 'new' ? undefined : editing} onClose={() => setEditing(null)} />}</>
}

function HistoryScreen() {
  const library = useLibrary(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('completed')
  const rooms = library.rooms.filter(room => (room.edition ?? 'classic') === library.settings.edition)
  const completed = rooms.filter(r => roomState(r)?.phase === 'results')
  const visible = [...rooms].filter(r => roomState(r) && (filter === 'all' || roomState(r)?.phase === 'results') && (r.name.toLowerCase().includes(query.toLowerCase()) || r.roster.some(p => p.name.toLowerCase().includes(query.toLowerCase())))).sort((a, b) => b.updatedAt - a.updatedAt)
  return <><PageHeading kicker="EVERY FLIP HAS A STORY" title="Match history" copy="Final scores and every round’s cards." /><section className="room-history-banner"><Trophy size={39} /><div><strong>{completed.length}</strong><span>game{completed.length === 1 ? '' : 's'} in the books</span></div><Sparkles size={23} /></section><div className="room-filter-tabs"><button className={filter === 'completed' ? 'selected' : ''} aria-pressed={filter === 'completed'} onClick={() => setFilter('completed')}>Completed</button><button className={filter === 'all' ? 'selected' : ''} aria-pressed={filter === 'all'} onClick={() => setFilter('all')}>All matches</button></div><label className="room-search"><Search size={18} /><input aria-label="Search match history" placeholder="Search rooms or players…" value={query} onChange={e => setQuery(e.target.value)} /></label><div className="room-section-heading"><h2>{filter === 'completed' ? 'Past game nights' : 'Your matches'}</h2><span className="room-section-note">{visible.length} {visible.length === 1 ? 'MATCH' : 'MATCHES'}</span></div><div className="room-list">{visible.map(r => <RoomCard key={r.id} room={r} />)}</div>{!visible.length && <EmptyState icon={<Medal size={32} />} title={query ? 'No matches found' : 'The best is yet to flip'}>{query ? 'Try another room or player name.' : filter === 'completed' ? 'Finish a match to see the final standings and every round’s cards here.' : 'Start a room to begin recording your games.'}</EmptyState>}</>
}

function RoomForm({ room, onDone }: { room?: Room; onDone?: () => void }) {
  const library = useLibrary(); const edition = room?.edition ?? library.settings.edition; const profiles = edition === 'vengeance' ? library.vengeancePlayers : library.players; const navigate = useAppNavigation(); const [name, setName] = useState(room?.name ?? ''); const [target, setTarget] = useState(room?.targetScore ?? (edition === 'vengeance' ? library.settings.vengeanceTargetScore : library.settings.targetScore)); const [roster, setRoster] = useState<PlayerProfile[]>(room?.roster ?? []); const [playerName, setPlayerName] = useState(''); const [error, setError] = useState(''); const [showPicker, setShowPicker] = useState(false); const [editingCharacter, setEditingCharacter] = useState<PlayerProfile | null>(null); const [removingPlayer, setRemovingPlayer] = useState<PlayerProfile | null>(null)
  const addPlayer = (profile?: PlayerProfile) => {
    const nextName = (profile?.name ?? playerName).trim()
    if (!nextName) return setError('Enter a player name first.')
    if (roster.length >= 18) return setError('A room can hold up to 18 players.')
    if (roster.some(p => p.name.toLowerCase() === nextName.toLowerCase())) return setError('That player is already at the table.')
    const existing = profiles.find(p => p.name.toLowerCase() === nextName.toLowerCase())
    setRoster([...roster, profile ?? existing ?? newProfile(nextName, roster.length)]); setPlayerName(''); setError('')
  }
  const move = (index: number, direction: -1 | 1) => { const next = [...roster];[next[index], next[index + direction]] = [next[index + direction], next[index]]; setRoster(next) }
  const removePlayer = (player: PlayerProfile) => {
    if (room?.state?.players.some(seated => seated.id === player.id) || room?.vengeanceState?.players.some(seated => seated.id === player.id)) setRemovingPlayer(player)
    else setRoster(current => current.filter(seated => seated.id !== player.id))
  }
  const saveCharacter = (player: PlayerProfile, avatar: PlayerAvatarId, color: string) => {
    const updated = { ...player, avatar, color }
    if (profiles.some(saved => saved.id === player.id)) savePlayerProfile(updated, edition)
    setRoster(current => current.map(seated => seated.id === player.id ? updated : seated))
    setError('')
  }
  const save = (begin: boolean) => {
    if (!name.trim()) return setError('Give your room a name.')
    if (roster.length < 2) return setError('Add at least 2 players to start your room.')
    if (!Number.isInteger(target) || target < 50 || target > 500) return setError('Choose a target between 50 and 500 points.')
    try {
      if (room) { editRoom(room, name, target, roster); if (onDone) onDone(); else navigate(`/room?id=${room.id}`); return }
      const created = createRoom(name, target, roster, edition)
      if (begin) { startRoom(created); navigate(roomPlayPath(created)) } else navigate(`/room?id=${created.id}`)
    } catch (e) { setError((e as Error).message) }
  }
  return <><div className="room-back-row"><button onClick={() => { if (room && onDone) onDone(); else navigate(room ? `/room?id=${room.id}` : '/landing') }}><ArrowLeft size={19} /> {room ? 'Back to room' : 'Your rooms'}</button></div><PageHeading kicker={edition === 'vengeance' ? 'SET UP YOUR VENGEANCE TABLE' : 'SET UP YOUR TABLE'} title={room ? 'Edit room' : 'New room'} copy={room ? 'Update players before the first card of the round.' : 'Name your room and add your players.'} />
    <section className="room-form-panel"><div className="room-form-section-title"><span>01</span><h2>Make it yours</h2><Flag size={21} /></div><label className="room-field">ROOM NAME<input placeholder="Friday night flips" maxLength={40} value={name} onChange={e => setName(e.target.value)} /></label><div className="room-field">TARGET SCORE<div className="room-target-options">{targetScorePresets.map(({ value, label }) => <button key={value} className={target === value ? 'selected' : ''} aria-pressed={target === value} onClick={() => setTarget(value)}>{value}<small>PTS</small><span>{label}</span></button>)}</div><label className="room-custom-target">Custom target<input type="number" min={50} max={500} aria-label="Custom target score" value={target || ''} onChange={e => setTarget(Number(e.target.value))} /></label></div></section>
    <section className="room-form-panel"><div className="room-form-section-title"><span>02</span><h2>Who’s at the table?</h2><b>{roster.length}/18</b></div><p className="room-muted">2–18 players. Arrange your crew in turn order.{room?.state && ' New players join with zero points.'}</p><div className="room-roster">{roster.map((p, i) => <div className="room-roster-row" key={p.id}><span className="room-seat">{String(i + 1).padStart(2, '0')}</span><button type="button" className="room-roster-avatar-edit" aria-label={`Edit ${p.name}'s character`} title={`Edit ${p.name}'s character`} onClick={() => setEditingCharacter(p)}><Avatar player={p} small /><Pencil size={13} /></button><b>{p.name}</b><div className="room-roster-controls"><button type="button" aria-label={`Move ${p.name} up`} disabled={i === 0} onClick={() => move(i, -1)}><ArrowUp size={14} /></button><button type="button" aria-label={`Move ${p.name} down`} disabled={i === roster.length - 1} onClick={() => move(i, 1)}><ArrowDown size={14} /></button><button type="button" className="room-roster-remove" aria-label={`Remove ${p.name} from room`} title={`Remove ${p.name} from room`} onClick={() => removePlayer(p)}><X size={16} /></button></div></div>)}</div>
      <div className="room-add-player"><input aria-label="New player name" maxLength={24} placeholder="Add a player’s name" value={playerName} onChange={e => setPlayerName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); addPlayer() } }} /><button aria-label="Add named player" disabled={roster.length >= 18} onClick={() => addPlayer()}><Plus size={20} /></button></div>
      {profiles.length > 0 && <><button className="room-pick-crew" aria-expanded={showPicker} onClick={() => setShowPicker(!showPicker)}><Users size={16} /> Choose saved players <ChevronDown size={15} /></button>{showPicker && <div className="room-saved-player-picker">{profiles.filter(p => !roster.some(r => r.id === p.id || r.name.toLowerCase() === p.name.toLowerCase())).map(p => <button key={p.id} onClick={() => addPlayer(p)}><Avatar player={p} small />{p.name}<Plus size={14} /></button>)}{profiles.every(p => roster.some(r => r.id === p.id)) && <p>Everyone’s at the table!</p>}</div>}</>}
    </section>{error && <p className="room-error" role="alert">{error}</p>}<div className="room-form-actions"><ActionButton onClick={() => save(!room)}><Play size={17} fill="currentColor" /> {room ? 'Save room changes' : 'Create & start playing'}</ActionButton>{!room && <ActionButton secondary onClick={() => save(false)}><FolderOpen size={17} /> Save room for later</ActionButton>}</div>{editingCharacter && <RoomCharacterDialog player={editingCharacter} onClose={() => setEditingCharacter(null)} onSave={(avatar, color) => saveCharacter(editingCharacter, avatar, color)} />}{removingPlayer && <ConfirmationModal variant="floating" eyebrow="REMOVE PLAYER" title={`Remove ${removingPlayer.name}?`} message="Saving this change removes their total from the current match. Completed round cards and scores stay in room history, and their saved player profile stays available." cancelLabel="Keep player" confirmLabel="Remove player" onCancel={() => setRemovingPlayer(null)} onConfirm={() => { setRoster(current => current.filter(player => player.id !== removingPlayer.id)); setRemovingPlayer(null); setError('') }} />}</>
}

function VengeanceRoomDetail({ room }: { room: Room }) {
  const navigate = useAppNavigation(); const [editing, setEditing] = useState(false); const [menu, setMenu] = useState(false); const [deletePrompt, setDeletePrompt] = useState(false); const [tvShareOpen, setTvShareOpen] = useState(false); const [error, setError] = useState(''); const [tab, setTab] = useState<'scores' | 'rounds'>('scores')
  const state = room.vengeanceState; const editable = canEditRoster(room)
  if (editing && editable) return <RoomForm room={room} onDone={() => { setEditing(false); window.requestAnimationFrame(() => window.scrollTo({ top: 0, behavior: 'auto' })) }} />
  const play = () => { try { if (!state) startRoom(room); navigate(roomPlayPath(room)) } catch (cause) { setError((cause as Error).message) } }
  const rematch = () => { try { const next = createRoom(`${room.name.slice(0, 30)} · Rematch`, room.targetScore, room.roster, 'vengeance'); navigate(`/room?id=${next.id}`) } catch (cause) { setError((cause as Error).message) } }
  const ordered = state ? [...state.players].sort((a, b) => b.totalScore - a.totalScore) : room.roster.map(p => ({ ...p, totalScore: 0 }))
  const winners = state?.phase === 'results' ? ordered.filter(p => p.totalScore >= room.targetScore && p.totalScore === ordered[0]?.totalScore).map(p => p.id) : []

  return <><div className="room-back-row"><button className="room-back-link" onClick={() => navigate('/landing')}><ArrowLeft size={19} /> Your rooms</button><div className="room-menu-wrapper"><button className="room-menu-trigger" aria-label="Room options" aria-expanded={menu} onClick={() => setMenu(!menu)}><MoreHorizontal size={19} /></button>{menu && <><div className="room-menu-backdrop" onClick={() => setMenu(false)} /><div className="room-options-popover" role="menu"><button className="room-delete-button" role="menuitem" onClick={() => { setMenu(false); setDeletePrompt(true) }}><Trash2 size={14} /> Delete room</button></div></>}</div></div>
    <section className="room-detail-hero"><span className={`room-badge ${state?.phase === 'results' ? 'done' : state ? 'live' : 'ready'}`}>{roomStatus(room)}</span><h1>{room.name}</h1><p>{room.roster.length} players <span>·</span> First to {room.targetScore} <span>·</span> {dateLabel(room.createdAt)}</p><div className="room-avatar-stack">{room.roster.slice(0, 8).map(p => <Avatar key={p.id} player={p} small />)}{room.roster.length > 8 && <span className="room-avatar more" aria-label={`${room.roster.length - 8} more players`}>+{room.roster.length - 8}</span>}</div>{state?.phase === 'results' ? <><button type="button" className="room-button room-view-results" onClick={() => navigate(roomPlayPath(room))}><Trophy size={18} /> View game results</button><ActionButton secondary onClick={rematch}><Plus size={18} /> Same crew, new match</ActionButton></> : <ActionButton onClick={play}><Play size={17} fill="currentColor" /> {state ? `Resume round ${state.roundNumber}` : 'Start this game'}</ActionButton>}</section>
    {error && <p className="room-error" role="alert">{error}</p>}{tvSharingAvailable() && <button className="room-dashed-action" onClick={() => setTvShareOpen(true)}><Monitor size={16} /> Show live scores on TV</button>}{editable && <button className="room-dashed-action" onClick={() => setEditing(true)}><Pencil size={16} /> Edit room & players</button>}
    <div className="room-filter-tabs detail-tabs"><button className={tab === 'scores' ? 'selected' : ''} onClick={() => setTab('scores')} aria-pressed={tab === 'scores'}><Trophy size={15} /> Standings</button><button className={tab === 'rounds' ? 'selected' : ''} onClick={() => setTab('rounds')} aria-pressed={tab === 'rounds'}><History size={15} /> Round history</button></div>
    {tab === 'scores' ? <><div className="room-section-heading"><h2>{state?.phase === 'results' ? 'Final standings' : 'The race so far'}</h2><span className="room-section-note">{state?.history.length ?? 0} ROUNDS</span></div><div className="room-standings">{ordered.map((player, index) => <div className={`room-standing ${winners.includes(player.id) ? 'winner' : ''}`} key={player.id}><span className="standing-rank">{winners.includes(player.id) ? <Trophy size={18} /> : String(index + 1).padStart(2, '0')}</span><Avatar player={player} small /><b>{player.name}</b><strong>{player.totalScore}<small>PTS</small></strong></div>)}</div>{state && <p className="room-local-note">Totals include completed rounds.</p>}{state && state.phase !== 'results' && <div className="room-current-note"><Play size={16} /><p>Round {state.roundNumber} is saved and waiting.<button onClick={play}>Back to the table <ArrowRight size={13} /></button></p></div>}</> : <><div className="room-section-heading"><h2>Every round. Every card.</h2></div>{state?.history.length ? [...state.history].reverse().map(round => <details className="room-round-detail" key={round.round}><summary><span className="round-number">{String(round.round).padStart(2, '0')}</span><div><b>Round {round.round}</b><small>{Object.keys(round.scores).length} players · scores & cards</small></div><ChevronDown size={19} /></summary><div className="room-round-hands">{Object.entries(round.hands).map(([playerId, hand]) => { const player = room.roster.find(item => item.id === playerId) ?? { id: playerId, name: hand.name ?? 'Former player', color: hand.color ?? '#132d67', avatar: hand.avatar }; return <article className="room-history-hand" key={player.id}><header><Avatar player={player} small /><b>{player.name}</b><span>{hand?.status === 'busted' ? 'BUST' : hand?.status === 'flip-seven' ? 'FLIP 7' : 'STAYED'}</span><strong>{round.scores[player.id] ?? 0}<small>pts</small></strong></header><div className="vengeance-history-cards">{hand?.entries.map(entry => <span key={entry.instanceId} title={entry.card.label}>{entry.card.label}<img src={cardThumbnailUrl(entry.card.image ?? '')} alt="" aria-hidden="true" onError={event => { event.currentTarget.style.display = 'none' }} /></span>)}{!hand?.entries.length && <small>No cards recorded</small>}</div></article> })}</div></details>) : <EmptyState icon={<History size={29} />} title="Your story starts on round one">Actions and card ownership will be kept with each round.</EmptyState>}</>}
    {tvShareOpen && <TvShareDialog roomId={room.id} onClose={() => setTvShareOpen(false)} />}{deletePrompt && <ConfirmationModal variant="floating" eyebrow="DELETE ROOM" title={`Delete ${room.name}?`} message="This removes this room and its card history. Completed lifetime stats stay with Vengeance players." cancelLabel="Keep room" confirmLabel="Delete room" onCancel={() => setDeletePrompt(false)} onConfirm={() => { try { updateLibrary(current => ({ ...current, rooms: current.rooms.filter(item => item.id !== room.id) })); navigate('/landing') } catch (cause) { setError((cause as Error).message); setDeletePrompt(false) } }} />}</>
}

function RoomDetail({ room }: { room: Room }) {
  const navigate = useAppNavigation(); const [editing, setEditing] = useState(false); const [menu, setMenu] = useState(false); const [deletePrompt, setDeletePrompt] = useState(false); const [tvShareOpen, setTvShareOpen] = useState(false); const [error, setError] = useState(''); const [tab, setTab] = useState('scores')
  const state = room.state; const editable = canEditRoster(room)
  if (editing && editable) return <RoomForm room={room} onDone={() => { setEditing(false); window.requestAnimationFrame(() => window.scrollTo({ top: 0, behavior: 'auto' })) }} />
  const play = () => { try { if (!state) startRoom(room); navigate(`/banker?room=${room.id}`) } catch (e) { setError((e as Error).message) } }
  const rematch = () => { try { const next = createRoom(`${room.name.slice(0, 30)} · Rematch`, room.targetScore, room.roster); navigate(`/room?id=${next.id}`) } catch (e) { setError((e as Error).message) } }
  const ordered = state ? [...state.players].sort((a, b) => b.totalScore - a.totalScore) : room.roster.map(p => ({ ...p, totalScore: 0 }))
  return <><div className="room-back-row"><button className="room-back-link" onClick={() => navigate('/landing')}><ArrowLeft size={19} /> Your rooms</button><div className="room-menu-wrapper"><button className="room-menu-trigger" aria-label="Room options" aria-expanded={menu} onClick={() => setMenu(!menu)}><MoreHorizontal size={19} /></button>{menu && <><div className="room-menu-backdrop" onClick={() => setMenu(false)} /><div className="room-options-popover" role="menu"><button className="room-delete-button" role="menuitem" onClick={() => { setMenu(false); setDeletePrompt(true) }}><Trash2 size={14} /> Delete room</button></div></>}</div></div>
    <section className="room-detail-hero"><span className={`room-badge ${state?.phase === 'results' ? 'done' : state ? 'live' : 'ready'}`}>{roomStatus(room)}</span><h1>{room.name}</h1><p>{room.roster.length} players <span>·</span> First to {room.targetScore} <span>·</span> {dateLabel(room.createdAt)}</p><div className="room-avatar-stack">{room.roster.slice(0, 8).map(p => <Avatar key={p.id} player={p} small />)}{room.roster.length > 8 && <span className="room-avatar more" aria-label={`${room.roster.length - 8} more players`}>+{room.roster.length - 8}</span>}</div>{state?.phase === 'results' ? <><button type="button" className="room-button room-view-results" onClick={() => navigate(`/banker?room=${room.id}`)}><Trophy size={18} /> View game results</button><ActionButton secondary onClick={rematch}><Plus size={18} /> Same crew, new match</ActionButton></> : <ActionButton onClick={play}><Play size={17} fill="currentColor" /> {state ? `Resume round ${state.roundNumber}` : 'Start this game'}</ActionButton>}</section>
    {error && <p className="room-error" role="alert">{error}</p>}{tvSharingAvailable() && <button className="room-dashed-action" onClick={() => setTvShareOpen(true)}><Monitor size={16} /> Show live scores on TV</button>}{editable && <button className="room-dashed-action" onClick={() => setEditing(true)}><Pencil size={16} /> Edit room & players</button>}
    <div className="room-filter-tabs detail-tabs"><button className={tab === 'scores' ? 'selected' : ''} onClick={() => setTab('scores')} aria-pressed={tab === 'scores'}><Trophy size={15} /> Standings</button><button className={tab === 'rounds' ? 'selected' : ''} onClick={() => setTab('rounds')} aria-pressed={tab === 'rounds'}><History size={15} /> Round history</button></div>
    {tab === 'scores' ? <><div className="room-section-heading"><h2>{state?.phase === 'results' ? 'Final standings' : 'The race so far'}</h2><span className="room-section-note">{state?.history.length ?? 0} ROUNDS</span></div><div className="room-standings">{ordered.map((p, i) => <div className={`room-standing ${state?.winnerIds.includes(p.id) ? 'winner' : ''}`} key={p.id}><span className="standing-rank">{state?.winnerIds.includes(p.id) ? <Trophy size={18} /> : String(i + 1).padStart(2, '0')}</span><Avatar player={p} small /><b>{p.name}</b><strong>{p.totalScore}<small>PTS</small></strong></div>)}</div>{state && <p className="room-local-note">Totals include completed rounds.</p>}</> : <><div className="room-section-heading"><h2>Every round. Every card.</h2></div>{state?.history.length ? [...state.history].reverse().map(round => <details className="room-round-detail" key={round.round}><summary><span className="round-number">{String(round.round).padStart(2, '0')}</span><div><b>Round {round.round}</b><small>{Object.keys(round.scores).length} players · scores & cards</small></div><ChevronDown size={19} /></summary><div className="room-round-hands">{Object.entries(round.scores).map(([id, score]) => { const hand = round.hands?.[id]; const player = hand ? { id, name: hand.name, color: hand.color, avatar: hand.avatar ?? room.roster.find(p => p.id === id)?.avatar } : room.roster.find(p => p.id === id); return <article className="room-history-hand" key={id}><header>{player && <Avatar player={player} small />}<b>{player?.name ?? 'Player'}</b><span className={`${hand?.status ?? 'stayed'}-label`}>{hand?.status === 'busted' ? 'BUST' : hand?.status === 'flip-seven' ? 'FLIP 7!' : hand?.status === 'frozen' ? 'FROZEN' : 'BANKED'}</span><strong>{score}<small>pts</small></strong></header><div className="room-history-cards">{hand?.entries.map(entry => <div className={entry.voided ? 'voided' : ''} key={entry.instanceId} title={entry.voided ? `${entry.card.label} · discarded` : entry.card.label}><CardArtwork card={entry.card} lazy />{entry.voided && <span>DISCARD</span>}</div>)}{!hand?.entries.length && <p>No cards recorded.</p>}</div></article> })}</div></details>) : <EmptyState icon={<History size={29} />} title="Your story starts on round one">Finish a round to save each player’s score and cards here.</EmptyState>}{state?.phase === 'round' && <div className="room-current-note"><Play size={16} /><p>Round {state.roundNumber} is saved and waiting.<button onClick={play}>Back to the table <ArrowRight size={13} /></button></p></div>}</>}
    {tvShareOpen && <TvShareDialog roomId={room.id} onClose={() => setTvShareOpen(false)} />}{deletePrompt && <ConfirmationModal variant="floating" eyebrow="DELETE ROOM" title={`Delete ${room.name}?`} message="This removes this room and its detailed match history. Saved player profiles and lifetime matches, wins, and best scores stay. Export a backup first if you want to keep the details." cancelLabel="Keep room" confirmLabel="Delete room" onCancel={() => setDeletePrompt(false)} onConfirm={() => { try { updateLibrary(current => ({ ...current, rooms: current.rooms.filter(r => r.id !== room.id) })); navigate('/landing') } catch (e) { setError((e as Error).message); setDeletePrompt(false) } }} />}</>
}

function SettingsScreen() {
  const library = useLibrary(); const navigate = useAppNavigation(); const input = useRef<HTMLInputElement>(null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [restore, setRestore] = useState<string | null>(null); const [exportPrompt, setExportPrompt] = useState(false); const [clear, setClear] = useState(false)
  const edition = library.settings.edition; const editionRooms = library.rooms.filter(room => (room.edition ?? 'classic') === edition)
  const bytes = storageBytes(library); const completed = editionRooms.filter(room => roomState(room)?.phase === 'results').length
  const update = (change: Parameters<typeof updateLibrary>[0]) => { try { updateLibrary(change); setError('') } catch (e) { setError((e as Error).message) } }
  const readBackup = async (file?: File) => { if (!file) return; try { if (file.size > STORAGE_LIMIT * 2) throw new Error('The backup file is too large.'); const raw = await file.text(); if (storageBytes(decodeLibrary(raw)) > STORAGE_LIMIT) throw new Error('This backup exceeds the 10 MB game-data limit.'); setRestore(raw); setError('') } catch (e) { setError(`Could not read backup. ${(e as Error).message}`) } if (input.current) input.current.value = '' }
  return <><PageHeading kicker="YOUR GAME, YOUR WAY" title="Settings" copy="Preferences, backups, and help." /><section className="room-storage-panel"><div className="room-section-heading"><h2><ShieldCheck size={21} /> Device storage</h2></div><p>Game data stays on this device. A backup includes both editions.</p><div className="storage-usage"><strong>{formatBytes(bytes)}</strong><span>used · {formatBytes(STORAGE_LIMIT)} save limit</span></div><div className="room-progress-track"><i style={{ width: `${Math.min(100, Math.max(1, bytes / STORAGE_LIMIT * 100))}%` }} /></div><div className="storage-counts"><span>{editionRooms.length} {editionRooms.length === 1 ? 'room' : 'rooms'}</span><span>{edition === 'vengeance' ? library.vengeancePlayers.length : library.players.length} players</span><span>{completed} completed</span></div><p className="storage-explanation">These counts show {edition === 'vengeance' ? 'Vengeance' : 'Classic'}. Clearing completed rooms here keeps this edition’s lifetime stats. Actual device storage limits may be lower.</p></section>
    <section className="room-settings-group"><h2>At your table</h2><div className="room-setting-row"><div><Flag size={20} /><span><b>Default target score</b><small>For your next {edition === 'vengeance' ? 'Vengeance' : 'Classic'} room</small></span></div><TargetScorePicker value={edition === 'vengeance' ? library.settings.vengeanceTargetScore : library.settings.targetScore} onChange={targetScore => update(current => ({ ...current, settings: { ...current.settings, [edition === 'vengeance' ? 'vengeanceTargetScore' : 'targetScore']: targetScore } }))} /></div><div className="room-setting-row"><div><Sparkles size={20} /><span><b>Calmer animations</b><small>A little less movement</small></span></div><button role="switch" aria-checked={library.settings.reducedMotion} aria-label="Calmer animations" className={`room-switch ${library.settings.reducedMotion ? 'on' : ''}`} onClick={() => update(current => ({ ...current, settings: { ...current.settings, reducedMotion: !current.settings.reducedMotion } }))}><span /></button></div></section>
    <section className="room-settings-group"><h2>Keep your memories</h2><button className="room-setting-row" onClick={() => setExportPrompt(true)}><div><Download size={20} /><span><b>Export a backup</b><small>Save to Files, Drive, or share</small></span></div><ChevronRight size={18} /></button><button className="room-setting-row" onClick={() => input.current?.click()}><div><Upload size={20} /><span><b>Restore a backup</b><small>Replace local data from a saved file</small></span></div><ChevronRight size={18} /></button><input ref={input} className="visually-hidden" type="file" accept=".json,application/json,text/plain,application/octet-stream,*/*" aria-label="Backup file" onChange={e => void readBackup(e.target.files?.[0])} /><button className="room-setting-row danger" disabled={!completed} onClick={() => setClear(true)}><div><Trash2 size={20} /><span><b>Clear completed rooms</b><small>Keep every unfinished game</small></span></div><ChevronRight size={18} /></button></section>
    <section className="room-settings-group"><h2>A little help</h2>{[['How to play', '/rules', CircleHelp], ['Practice table', '/demo', Play], ['Questions & answers', '/faq', CircleHelp], ['Privacy & local data', '/privacy', ShieldCheck], ['Terms & conditions', '/terms', ShieldCheck], ['Contact & feedback', '/contact', CircleHelp]].map(([label, path, Icon]) => { const I = Icon as typeof CircleHelp; return <button key={String(path)} className="room-setting-row" onClick={() => navigate(String(path))}><div><I size={20} /><b>{String(label)}</b></div><ChevronRight size={18} /></button> })}</section>{error && <p className="room-error" role="alert">{error}</p>}{notice && <p className="room-success" role="status">{notice}</p>}<AppFooter />
    {exportPrompt && <ConfirmationModal variant="floating" eyebrow="BACK UP YOUR GAME" title="Export your local data?" message="This packages your rooms, player profiles, lifetime stats, and settings so you can choose where to save or share your backup file." cancelLabel="Cancel" confirmLabel="Export backup" onCancel={() => setExportPrompt(false)} onConfirm={async () => { setExportPrompt(false); try { const res = await exportBackup(); if (!res.canceled) { setError(''); setNotice('Backup ready! Saved or shared to your chosen destination.') } } catch (e) { setError((e as Error).message) } }} />}{restore && <ConfirmationModal variant="floating" eyebrow="RESTORE BACKUP" title="Replace your local library?" message="Rooms, player profiles, lifetime stats, and preferences will be replaced by this backup. Export your current library first if you want to keep it." cancelLabel="Keep current data" confirmLabel="Restore backup" onCancel={() => setRestore(null)} onConfirm={() => { try { restoreBackup(restore); setNotice('Backup restored. Your rooms are ready.'); setRestore(null) } catch (e) { setError((e as Error).message); setRestore(null) } }} />}{clear && <ConfirmationModal variant="floating" eyebrow="FREE UP SPACE" title={`Clear ${completed} completed ${completed === 1 ? 'room' : 'rooms'}?`} message="Detailed scores and card history will be removed. Lifetime matches, wins, and best scores stay, along with unfinished games and player profiles. Export a backup first to keep the details." cancelLabel="Keep completed rooms" confirmLabel="Clear completed" onCancel={() => setClear(false)} onConfirm={() => { try { updateLibrary(current => ({ ...current, rooms: current.rooms.filter(r => (r.edition ?? 'classic') !== edition || roomState(r)?.phase !== 'results') })); setError(''); setNotice('Completed history cleared. Lifetime player stats kept.'); setClear(false) } catch (e) { setError((e as Error).message); setClear(false) } }} />}</>
}

export function MobileApp({ page, roomId }: { page: MobilePage; roomId?: string }) {
  const library = useLibrary(); const error = getStorageError(); const navigate = useAppNavigation()
  const keyboardVisible = useKeyboardVisible()
  const room = library.rooms.find(r => r.id === roomId)
  const edition = room?.edition ?? library.settings.edition
  const nextEdition: Edition = edition === 'classic' ? 'vengeance' : 'classic'
  const showEditionFab = page === 'home' || page === 'players' || page === 'history' || page === 'settings'
  useEffect(() => {
    if (page === 'room' && room && room.edition !== library.settings.edition) {
      try { updateLibrary(current => ({ ...current, settings: { ...current.settings, edition: room.edition ?? 'classic' } })) }
      catch { /* The room is still readable if storage is unavailable. */ }
    }
  }, [page, room?.id, room?.edition, library.settings.edition])
  useEffect(() => { document.documentElement.classList.add('room-app-active'); return () => { document.documentElement.classList.remove('room-app-active') } }, [])
  const switchEdition = (next: Edition) => {
    if (next === library.settings.edition) return
    try { updateLibrary(current => ({ ...current, settings: { ...current.settings, edition: next } })) }
    catch (cause) { window.alert((cause as Error).message) }
  }
  return <div className={`room-app-shell edition-${edition}`}><main className={`room-app-main page-${page}`}>{page !== 'room' && <PageArtwork edition={edition} />}{error && <p className="room-error" role="alert">{error}</p>}{page === 'home' ? <HomeScreen /> : page === 'players' ? <PlayersScreen /> : page === 'history' ? <HistoryScreen /> : page === 'settings' ? <SettingsScreen /> : page === 'new' ? <RoomForm /> : room ? room.edition === 'vengeance' ? <VengeanceRoomDetail key={room.id} room={room} /> : <RoomDetail key={room.id} room={room} /> : <EmptyState icon={<FolderOpen size={30} />} title="This room isn’t here">It may have been removed or restored from a different backup.<ActionButton onClick={() => navigate('/landing')}>Back to your rooms</ActionButton></EmptyState>}</main>{showEditionFab && !keyboardVisible && <EditionFab target={nextEdition} onSwitch={() => switchEdition(nextEdition)} />}<BottomNav page={page} /></div>
}
